const app=document.querySelector("#app"),sheet=document.querySelector("#sheet");let view="today";
const entries=[
 {id:1,type:"note",icon:"📝",title:"Fluidoterapia",meta:"Internamento · ontem · Joana",text:"Rever cálculo e monitorização da fluidoterapia.",favorite:false},
 {id:2,type:"question",icon:"❓",title:"Administração de medicação",meta:"Farmácia · 30 set · Pendente",text:"Confirmar boas práticas na administração de medicação.",favorite:false,status:"pending"},
 {id:3,type:"procedure",icon:"📚",title:"Cateter periférico",meta:"Procedimento · atualizado 28 set",text:"Procedimento em construção.",favorite:true}
];
const nav=[...document.querySelectorAll("nav button")];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const recent=()=>entries.slice(0,5).map(e=>`<button class="recent-item recent-button" data-entry="${e.id}"><div class="item-icon">${e.icon}</div><div class="item-main"><div class="item-title">${esc(e.title)}</div><div class="item-meta">${esc(e.meta)}</div></div><div class="chev">›</div></button>`).join("");
function bindEntries(){document.querySelectorAll("[data-entry]").forEach(b=>b.onclick=()=>openEntry(Number(b.dataset.entry)))}
function render(){
 nav.forEach(b=>b.classList.toggle("active",b.dataset.view===view));
 if(view==="today")app.innerHTML='<h1>Olá, Rute</h1><div class="muted">Sexta-feira, 2 de outubro</div><div class="card primary-card"><button class="new-btn" id="newEntry">＋ Novo<small>Nota ou dúvida</small></button></div><div class="eyebrow">Hoje</div><div class="card"><div class="row"><div><div class="area">Receção</div><div class="muted small">Formação com Sandra</div></div><b>09:00–20:00</b></div><div class="summary"><span class="pill">📝 3 notas</span><span class="pill">❓ 1 dúvida</span></div><button class="btn secondary">Ver o dia</button></div><div class="eyebrow">Continuar</div><div class="card"><div class="continue-item">❓ <div class="item-main item-title">2 dúvidas pendentes</div><div class="chev">›</div></div><div class="continue-item">⭐ <div class="item-main item-title">Favoritos</div><div class="chev">›</div></div></div><div class="eyebrow">Recentes</div><div class="card">'+recent()+'</div>';
 else if(view==="notebook")app.innerHTML='<h1>Caderno</h1><div class="muted">O teu diário de aprendizagem</div><div class="card">'+recent()+'</div>';
 else if(view==="learn")app.innerHTML='<h1>Aprender</h1><div class="muted">Procedimentos e evolução</div><div class="card placeholder">📚<h2>O teu manual pessoal</h2><div class="muted">Aqui vão viver os procedimentos e o histórico de aprendizagem.</div></div>';
 else app.innerHTML='<h1>Procurar</h1><div class="muted">Pesquisa global no teu caderno</div><div class="card"><input class="searchbox" id="searchInput" placeholder="Pesquisar notas, dúvidas, procedimentos…"><div id="searchResults"></div></div>';
 const n=document.querySelector("#newEntry");if(n)n.onclick=openType;bindEntries();
 const si=document.querySelector("#searchInput");if(si)si.oninput=()=>{const q=si.value.trim().toLowerCase(),box=document.querySelector("#searchResults");if(!q){box.innerHTML="";return}const found=entries.filter(e=>(e.title+" "+e.meta+" "+e.text).toLowerCase().includes(q));box.innerHTML=found.length?found.map(e=>`<button class="recent-item recent-button" data-entry="${e.id}"><div class="item-icon">${e.icon}</div><div class="item-main"><div class="item-title">${esc(e.title)}</div><div class="item-meta">${esc(e.meta)}</div></div><div class="chev">›</div></button>`).join(""):'<div class="muted small search-empty">Sem resultados.</div>';bindEntries()}
}
nav.forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
function close(){sheet.classList.add("hidden");sheet.innerHTML=""}
function openType(){sheet.classList.remove("hidden");sheet.innerHTML='<div class="sheet-panel"><div class="sheet-handle"></div><div class="row"><div class="sheet-title">Novo registo</div><button class="close" id="x">×</button></div><div class="type-grid"><button class="type-btn" data-t="Nota"><b>📝</b>Nota</button><button class="type-btn" data-t="Dúvida"><b>❓</b>Dúvida</button></div></div>';document.querySelector("#x").onclick=close;document.querySelectorAll(".type-btn").forEach(b=>b.onclick=()=>editor(b.dataset.t))}
function editor(t){
 const label=t==="Dúvida"?"Qual é a tua dúvida?":"O que aprendeste?";
 sheet.innerHTML=`<div class="sheet-panel"><div class="sheet-handle"></div><div class="row"><div class="sheet-title">Nova ${t.toLowerCase()}</div><button class="close" id="x">×</button></div><div class="field"><label>${label}</label><textarea id="txt" placeholder="Escreve aqui…" autofocus></textarea></div><details class="details"><summary>Adicionar detalhes</summary><div class="field"><label>Área</label><select id="area"><option>Receção — sugerido pela escala</option><option>Internamento</option><option>Consultas</option><option>Cirurgia</option><option>Laboratório</option><option>Imagiologia</option><option>Farmácia / Medicação</option><option>Emergência / UCI</option><option value="__new">+ Nova área…</option></select><div id="newArea"></div></div><div class="field"><label>Tema</label><select id="theme"><option>Selecionar…</option><option value="__new">+ Novo tema…</option></select><div id="newTheme"></div></div><div class="field"><label>Pessoa</label><select id="person"><option>Sandra — sugerido pela escala</option><option>Joana</option><option value="__new">+ Nova pessoa…</option></select><div id="newPerson"></div></div></details><button class="btn" id="save">Guardar</button><div class="muted small center-note">Data e hora são registadas automaticamente.</div></div>`;
 document.querySelector("#x").onclick=close;setTimeout(()=>document.querySelector("#txt")?.focus(),50);
 [["area","newArea","área"],["theme","newTheme","tema"],["person","newPerson","pessoa"]].forEach(([id,target,label])=>document.querySelector("#"+id).onchange=e=>{if(e.target.value==="__new")inlineNew(id,target,label)});
 document.querySelector("#save").onclick=()=>{const v=document.querySelector("#txt").value.trim();if(!v)return;const isQ=t==="Dúvida";entries.unshift({id:Date.now(),type:isQ?"question":"note",icon:isQ?"❓":"📝",title:v.length>42?v.slice(0,42)+"…":v,meta:isQ?"Agora · Pendente":"Agora · por organizar",text:v,favorite:false,status:isQ?"pending":null});close();view="notebook";render()}
}
function inlineNew(selectId,targetId,label){const box=document.querySelector("#"+targetId);box.innerHTML=`<div class="inline-create"><input id="${targetId}Input" placeholder="Nome da ${label}"><button type="button" id="${targetId}Btn">Criar</button></div>`;const input=document.querySelector("#"+targetId+"Input");input.focus();document.querySelector("#"+targetId+"Btn").onclick=()=>{const name=input.value.trim();if(!name)return;const s=document.querySelector("#"+selectId),o=document.createElement("option");o.textContent=name;o.value=name;s.insertBefore(o,s.querySelector('option[value="__new"]'));s.value=name;box.innerHTML=""}}
function openEntry(id){const e=entries.find(x=>x.id===id);if(!e)return;sheet.classList.remove("hidden");const q=e.type==="question";sheet.innerHTML=`<div class="sheet-panel"><div class="sheet-handle"></div><div class="row"><div><div class="entry-kind">${q?"Dúvida":e.type==="procedure"?"Procedimento":"Nota"}</div><div class="sheet-title entry-title">${esc(e.title)}</div></div><button class="close" id="x">×</button></div><div class="card entry-card"><div class="entry-text">${esc(e.text)}</div><div class="item-meta entry-meta">${esc(e.meta)}</div></div><div class="entry-actions"><button class="btn secondary" id="fav">${e.favorite?"★ Favorito":"☆ Favoritar"}</button><button class="btn secondary" id="edit">Editar</button></div>${q?questionBlock(e):""}</div>`;document.querySelector("#x").onclick=close;document.querySelector("#fav").onclick=()=>{e.favorite=!e.favorite;openEntry(id)};document.querySelector("#edit").onclick=()=>editEntry(e);if(q&&e.status==="pending")document.querySelector("#answer").onclick=()=>answerQuestion(e)}
function questionBlock(e){return e.status==="answered"?`<div class="eyebrow">Resposta</div><div class="card"><div class="entry-text">${esc(e.answer)}</div><div class="item-meta">Respondida por ${esc(e.answeredBy||"—")} · agora</div></div>`:'<div class="question-status">❓ Dúvida pendente</div><button class="btn" id="answer">Adicionar resposta</button>'}
function editEntry(e){sheet.innerHTML=`<div class="sheet-panel"><div class="sheet-handle"></div><div class="row"><div class="sheet-title">Editar registo</div><button class="close" id="x">×</button></div><div class="field"><label>Texto</label><textarea id="editText">${esc(e.text)}</textarea></div><button class="btn" id="saveEdit">Guardar alterações</button></div>`;document.querySelector("#x").onclick=close;document.querySelector("#saveEdit").onclick=()=>{const v=document.querySelector("#editText").value.trim();if(!v)return;e.text=v;e.title=v.length>42?v.slice(0,42)+"…":v;e.meta=e.meta.replace(/Agora|ontem|30 set/,"Agora");openEntry(e.id);render()}}
function answerQuestion(e){sheet.innerHTML=`<div class="sheet-panel"><div class="sheet-handle"></div><div class="row"><div class="sheet-title">Responder à dúvida</div><button class="close" id="x">×</button></div><div class="card"><b>${esc(e.title)}</b></div><div class="field"><label>Resposta</label><textarea id="answerText" placeholder="O que ficaste a saber?"></textarea></div><div class="field"><label>Quem respondeu?</label><select id="answeredBy"><option value="">Selecionar…</option><option>Sandra</option><option>Joana</option></select></div><button class="btn" id="saveAnswer">Guardar resposta</button></div>`;document.querySelector("#x").onclick=close;document.querySelector("#saveAnswer").onclick=()=>{const a=document.querySelector("#answerText").value.trim();if(!a)return;e.answer=a;e.answeredBy=document.querySelector("#answeredBy").value;e.status="answered";e.meta=e.meta.replace("Pendente","Respondida");openEntry(e.id);render()}}
sheet.onclick=e=>{if(e.target===sheet)close()};
document.querySelector("#menuBtn").onclick=()=>{sheet.classList.remove("hidden");sheet.innerHTML='<div class="sheet-panel"><div class="sheet-handle"></div><div class="row"><div class="sheet-title">Caderno Veterinário</div><button class="close" id="x">×</button></div><div class="card"><div class="continue-item">Gerir áreas e temas</div><div class="continue-item">Gerir pessoas</div><div class="continue-item">Exportar dados</div></div><div class="muted small">Protótipo V0.1 · dados fictícios</div></div>';document.querySelector("#x").onclick=close};render();